# El método de k-means

In [11]:
import numpy as np

In [12]:
data = np.random.random(90).reshape(30,3)
data

array([[0.26087317, 0.36229589, 0.77314768],
       [0.04256762, 0.9951264 , 0.82326281],
       [0.13635984, 0.91223454, 0.64032505],
       [0.01763639, 0.10865866, 0.27542139],
       [0.7024126 , 0.21779238, 0.94736732],
       [0.89513582, 0.02842453, 0.13358897],
       [0.84710767, 0.7415785 , 0.86012183],
       [0.26786765, 0.20739257, 0.12959581],
       [0.73168191, 0.1385192 , 0.64353867],
       [0.8706227 , 0.82544335, 0.20965378],
       [0.69565017, 0.41157124, 0.49059049],
       [0.2334435 , 0.05350097, 0.21948662],
       [0.64715089, 0.75940459, 0.6812172 ],
       [0.74593882, 0.41170748, 0.57233969],
       [0.20227098, 0.23234978, 0.01738266],
       [0.49727059, 0.38950928, 0.28787361],
       [0.66910417, 0.93662493, 0.35817785],
       [0.29031818, 0.76766876, 0.23166185],
       [0.00811217, 0.46626241, 0.33717924],
       [0.82429721, 0.98200905, 0.22683165],
       [0.36807705, 0.87653336, 0.73475334],
       [0.17044233, 0.98085937, 0.68872105],
       [0.

In [13]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.20227098, 0.23234978, 0.01738266],
       [0.26087317, 0.36229589, 0.77314768]])

In [14]:
from scipy.cluster.vq import vq

In [15]:
clusters = vq(data, clust_centers)
clusters

(array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 1, 0], dtype=int32),
 array([0.        , 0.67129971, 0.5792909 , 0.34054868, 0.49617619,
        0.73154023, 0.70362681, 0.13235399, 0.53715488, 0.91401433,
        0.52086243, 0.27167008, 0.56156657, 0.52730829, 0.        ,
        0.42998748, 0.81774468, 0.58329606, 0.44122853, 0.99638072,
        0.52669438, 0.63081406, 0.74481731, 0.70840237, 0.62516971,
        0.45187231, 0.2439061 , 0.32504741, 0.51884597, 0.27792706]))

In [16]:
labels = clusters[0]
labels

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0], dtype=int32)

In [45]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply
import chart_studio.plotly as ply

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 


In [46]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


NameError: name 'go' is not defined

In [47]:
from scipy.cluster.vq import kmeans

In [48]:
kmeans(data, clust_centers)

(array([[0.4177679 , 0.26942487, 0.28769385],
        [0.48468081, 0.75644318, 0.56547329]]), 0.3988680500863191)

In [49]:
kmeans(data, 2)

(array([[0.44458677, 0.28022023, 0.37179815],
        [0.46505141, 0.85471501, 0.51959369]]), 0.39510167764281884)